// Application & Admin Configuration Constants

export const ADMIN_EMAILS = [
  'admin@vyaparcare.com',
  'vyaparcareconsultancy@gmail.com',
  'nishant@vyaparcare.com',
];

export const SERVICE_CONFIG = {
  gst: {
    name: 'GST Registration',
    shortName: 'GST',
    icon: '🔖',
    color: 'bg-blue-100 text-blue-800 border-blue-200',
    badgeColor: '#3B82F6',
    route: '/dashboard/gst',
    table: 'gst_applications',
    defaultFee: 10000,
    processingDays: '3-7 working days',
  },
  plc: {
    name: 'Private Limited Company (PLC)',
    shortName: 'PLC',
    icon: '🏢',
    color: 'bg-purple-100 text-purple-800 border-purple-200',
    badgeColor: '#8B5CF6',
    route: '/dashboard/plc',
    table: 'plc_applications',
    defaultFee: 15000,
    processingDays: '10-14 working days',
  },
  trademark: {
    name: 'Trademark Registration',
    shortName: 'Trademark',
    icon: '™️',
    color: 'bg-amber-100 text-amber-800 border-amber-200',
    badgeColor: '#F59E0B',
    route: '/dashboard/trademark',
    table: 'tm_applications',
    defaultFee: 8000,
    processingDays: '1-3 working days for filing',
  },
  fssai: {
    name: 'FSSAI Food License',
    shortName: 'FSSAI',
    icon: '🍽️',
    color: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    badgeColor: '#10B981',
    route: '/dashboard/fssai',
    table: 'fssai_applications',
    defaultFee: 5000,
    processingDays: '7-10 working days',
  },
  iec: {
    name: 'Import Export Code (IEC)',
    shortName: 'IEC',
    icon: '🌐',
    color: 'bg-cyan-100 text-cyan-800 border-cyan-200',
    badgeColor: '#06B6D4',
    route: '/dashboard/iec',
    table: 'iec_applications',
    defaultFee: 4500,
    processingDays: '2-4 working days',
  },
  itr: {
    name: 'ITR Filing',
    shortName: 'ITR',
    icon: '📄',
    color: 'bg-yellow-100 text-yellow-800 border-yellow-200',
    badgeColor: '#EAB308',
    route: '/dashboard/itr',
    table: 'itr_applications',
    defaultFee: 3000,
    processingDays: '2-3 working days',
  },
  udyam: {
    name: 'MSME / Udyam Registration',
    shortName: 'Udyam',
    icon: '🏭',
    color: 'bg-pink-100 text-pink-800 border-pink-200',
    badgeColor: '#EC4899',
    route: '/dashboard/udyam',
    table: 'udyam_applications',
    defaultFee: 2000,
    processingDays: '1-2 working days',
  },
  other: {
    name: 'Other Consultancy Services',
    shortName: 'Other',
    icon: '⚙️',
    color: 'bg-slate-100 text-slate-800 border-slate-200',
    badgeColor: '#64748B',
    route: '/dashboard/other',
    table: 'other_service_requests',
    defaultFee: 3500,
    processingDays: 'Custom timeline',
  },
};

export const STATUS_DEFINITIONS = {
  new: { label: 'New', bg: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200' },
  pending: { label: 'Pending', bg: 'bg-amber-50', text: 'text-amber-700', border: 'border-amber-200' },
  submitted: { label: 'Submitted', bg: 'bg-cyan-50', text: 'text-cyan-700', border: 'border-cyan-200' },
  payment_pending: { label: 'Payment Pending', bg: 'bg-orange-50', text: 'text-orange-700', border: 'border-orange-200' },
  documents_pending: { label: 'Docs Pending', bg: 'bg-rose-50', text: 'text-rose-700', border: 'border-rose-200' },
  documents_uploaded: { label: 'Docs Uploaded', bg: 'bg-teal-50', text: 'text-teal-700', border: 'border-teal-200' },
  under_review: { label: 'Under Review', bg: 'bg-purple-50', text: 'text-purple-700', border: 'border-purple-200' },
  under_scrutiny: { label: 'Under Scrutiny', bg: 'bg-purple-50', text: 'text-purple-700', border: 'border-purple-200' },
  clarification_required: { label: 'Clarification Needed', bg: 'bg-orange-50', text: 'text-orange-700', border: 'border-orange-200' },
  clarification_requested: { label: 'Clarification Needed', bg: 'bg-orange-50', text: 'text-orange-700', border: 'border-orange-200' },
  clarification_needed: { label: 'Clarification Needed', bg: 'bg-orange-50', text: 'text-orange-700', border: 'border-orange-200' },
  mca_filed: { label: 'MCA Filed', bg: 'bg-indigo-50', text: 'text-indigo-700', border: 'border-indigo-200' },
  inspection_scheduled: { label: 'Inspection Scheduled', bg: 'bg-yellow-50', text: 'text-yellow-700', border: 'border-yellow-200' },
  approved: { label: 'Approved', bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200' },
  gstin_issued: { label: 'GSTIN Issued', bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200' },
  certificate_generated: { label: 'Certificate Issued', bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200' },
  completed: { label: 'Completed', bg: 'bg-emerald-100', text: 'text-emerald-800', border: 'border-emerald-300' },
  rejected: { label: 'Rejected', bg: 'bg-red-50', text: 'text-red-700', border: 'border-red-200' },
  failed: { label: 'Failed', bg: 'bg-red-50', text: 'text-red-700', border: 'border-red-200' },
  success: { label: 'Success', bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200' },
};

export const NOTIFICATION_TEMPLATES = [
  {
    title: 'Payment Reminder',
    type: 'payment',
    message: 'Dear Customer, your service application is awaiting payment. Kindly complete the pending installment to avoid processing delays.',
  },
  {
    title: 'Document Request',
    type: 'action',
    message: 'Dear Customer, additional/clear documents are required for your application. Please log in to your account and upload the requested files.',
  },
  {
    title: 'Service Update',
    type: 'info',
    message: 'Your application has successfully entered the next stage with the regulatory department. We are actively tracking its progress.',
  },
  {
    title: 'Application Approved',
    type: 'success',
    message: 'Congratulations! Your application has been approved and your official certificate / registration document has been issued.',
  },
];
