/**
 * Central Configuration for All Business, Tax, Legal & Compliance Services
 * Used across the 4 Navigation Tabs:
 * Tab 1: Tax / Accounting / Company
 * Tab 2: Insurance Services (ProFin)
 * Tab 3: Marketing Services
 * Tab 4: Web & Digital Services
 */

// =========================================================================
// TAB 1: 34 TAX, ACCOUNTING & COMPANY SERVICES (2-COLUMN GRID)
// =========================================================================
export const TAX_COMPANY_SERVICES = [
  // GST Services
  {
    id: 'gst-registration',
    name: 'GST Registration',
    icon: '📋',
    category: 'GST',
    tags: ['Popular', 'GST', 'Registration'],
    fee: 10000,
    processingDays: '3-5 Working Days',
    description: 'New GST Registration for Proprietorship, Partnership, LLP or Company.',
    targetScreen: 'GSTConstitution',
    whatsIncluded: ['GSTIN Allotment', 'GST Certificate', 'HSN Mapping', 'Govt Portal Filing'],
  },
  {
    id: 'gst-returns',
    name: 'GST Returns',
    icon: '📊',
    category: 'GST',
    tags: ['Popular', 'GST', 'Filing'],
    fee: 1500,
    processingDays: '1-2 Working Days',
    description: 'Monthly & quarterly GSTR-1, GSTR-3B and GSTR-9 annual return filings.',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['GSTR-1 & 3B Filing', 'Input Tax Credit (ITC) Check', 'Tax Challan Support'],
  },
  {
    id: 'gst-revocation',
    name: 'GST Revocation',
    icon: '🔄',
    category: 'GST',
    tags: ['GST', 'Filing'],
    fee: 3500,
    processingDays: '7-10 Working Days',
    description: 'Revoke and restore cancelled GSTIN from jurisdictional tax department.',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['Dept Application Filing', 'Show Cause Notice Reply', 'Officer Liaisoning'],
  },
  {
    id: 'gst-notice-response',
    name: 'GST Notice Response',
    icon: '⚖️',
    category: 'GST',
    tags: ['GST', 'Filing'],
    fee: 3000,
    processingDays: '3-5 Working Days',
    description: 'Professional legal drafting and reply submission for ASMT-10, DRC-01 notices.',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['Notice Scrutiny', 'Legal Reply Drafting', 'Portal Submission & Hearing Prep'],
  },
  {
    id: 'gst-amendment',
    name: 'GST Amendment',
    icon: '📝',
    category: 'GST',
    tags: ['GST', 'Registration'],
    fee: 2000,
    processingDays: '2-4 Working Days',
    description: 'Core and non-core field modifications (Address, Director, HSN, Bank).',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['Core / Non-Core Amendment', 'Document Verification', 'Updated Certificate'],
  },
  {
    id: 'gst-lut',
    name: 'GST LUT Filing',
    icon: '📄',
    category: 'GST',
    tags: ['GST', 'Filing'],
    fee: 1500,
    processingDays: '1 Working Day',
    description: 'Letter of Undertaking (LUT) for zero-rated export of goods and services.',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['Form RFD-11 LUT Filing', 'Annual Validity ARN', 'Zero-Duty Export Eligibility'],
  },
  {
    id: 'gst-surrender',
    name: 'GST Surrender',
    icon: '🛑',
    category: 'GST',
    tags: ['GST', 'Filing'],
    fee: 2500,
    processingDays: '5-7 Working Days',
    description: 'Formal application for closure and surrender of inactive/defunct GSTIN.',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['Final GSTR-10 Return', 'Cancellation Order Application', 'No-Dues Clearance'],
  },
  {
    id: 'gst-reconciliation',
    name: 'GST Reconciliation',
    icon: '🔍',
    category: 'GST',
    tags: ['GST', 'Accounting'],
    fee: 2500,
    processingDays: '2-3 Working Days',
    description: 'Reconciliation of GSTR-2B with Purchase Register (Books vs Portal).',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['GSTR-2B vs Books Report', 'Mismatched Invoices Flagging', 'ITC Maximization'],
  },
  {
    id: 'gst-pmt-09',
    name: 'GST PMT-09',
    icon: '💳',
    category: 'GST',
    tags: ['GST', 'Filing'],
    fee: 1200,
    processingDays: '1 Working Day',
    description: 'Transfer misallocated cash ledger balances between CGST, SGST, IGST heads.',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['Cash Ledger Balance Transfer', 'Form PMT-09 E-Filing', 'Instant Ledger Adjustment'],
  },
  {
    id: 'gst-eway-bill',
    name: 'E-way Bill',
    icon: '🚚',
    category: 'GST',
    tags: ['GST', 'Filing'],
    fee: 1000,
    processingDays: 'Same Day',
    description: 'E-way bill generation and system setup for consignments.',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['Part A & Part B Generation', 'Consolidated E-way Bill', 'Transporter Mapping'],
  },

  // Accounting & Tax
  {
    id: 'tds-return',
    name: 'TDS Return Filing',
    icon: '🧾',
    category: 'Accounting',
    tags: ['Accounting', 'Filing'],
    fee: 2500,
    processingDays: '2-3 Working Days',
    description: 'Quarterly Form 24Q, 26Q, 27Q filings and Form 16/16A generation.',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['FVU File Preparation', 'TRACES Upload', 'Form 16/16A Generation'],
  },
  {
    id: 'itr-filing',
    name: 'ITR & Audit',
    icon: '📈',
    category: 'Accounting',
    tags: ['Popular', 'Accounting', 'Filing'],
    fee: 3000,
    processingDays: '2-3 Working Days',
    description: 'Annual ITR filing for individuals, businesses & Section 44AB audits.',
    targetScreen: 'ITRProfile',
    whatsIncluded: ['ITR-1/2/3/4 Filing', 'Computation Sheet', 'AIS/26AS Match', 'ITR-V Ack'],
  },
  {
    id: 'monthly-accounting',
    name: 'Monthly Accounting',
    icon: '📚',
    category: 'Accounting',
    tags: ['Popular', 'Accounting'],
    fee: 5000,
    processingDays: 'Monthly Retainer',
    description: 'Monthly Tally/Zoho ledger maintenance & bank reconciliation.',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['Double-Entry Bookkeeping', 'Monthly P&L & Balance Sheet', 'Tax Compliance Review'],
  },
  {
    id: 'balance-sheet',
    name: 'Balance Sheet',
    icon: '📑',
    category: 'Accounting',
    tags: ['Accounting'],
    fee: 6000,
    processingDays: '3-5 Working Days',
    description: 'Audited Financial Statements, CMA Preparation & CA certified balance sheets.',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['CA Certified Balance Sheet', 'Profit & Loss Statement', 'Notes to Accounts'],
  },

  // Company Compliances & ROC
  {
    id: 'company-registration',
    name: 'Company Registration',
    icon: '🏢',
    category: 'Company',
    tags: ['Popular', 'Company', 'Registration'],
    fee: 15000,
    processingDays: '7-10 Working Days',
    description: 'Private Limited, OPC or LLP incorporation with MCA SPICe+.',
    targetScreen: 'PLCApplicant',
    whatsIncluded: ['COI (Incorporation Cert)', 'PAN, TAN & 2 DINs', 'MOA & AOA Drafting', 'Name Approval'],
  },
  {
    id: 'company-closing',
    name: 'Company Closing',
    icon: '🔒',
    category: 'Company',
    tags: ['Company', 'Filing'],
    fee: 12000,
    processingDays: '15-20 Working Days',
    description: 'Strike off defunct company via Form STK-2 fast track exit route.',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['Form STK-2 Preparation', 'Indemnity Bond & Affidavits', 'RoC Strike-off Order'],
  },
  {
    id: 'company-conversion',
    name: 'Company Conversion',
    icon: '🔁',
    category: 'Company',
    tags: ['Company'],
    fee: 14000,
    processingDays: '10-14 Working Days',
    description: 'Conversion from Partnership to LLP, OPC to Pvt Ltd, or Pvt Ltd to Public Ltd.',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['Special Resolution Drafting', 'Form MGT-14 & INC-6/18', 'Fresh Certificate of Inc'],
  },
  {
    id: 'company-kyc',
    name: 'Company KYC',
    icon: '🆔',
    category: 'Company',
    tags: ['Company', 'Filing'],
    fee: 2500,
    processingDays: '2 Working Days',
    description: 'INC-20A Commencement of Business & MCA ACTIVE Form INC-22A.',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['INC-20A / INC-22A E-Filing', 'Bank Proof Validation', 'RoC SRN Acknowledgment'],
  },
  {
    id: 'company-alteration',
    name: 'Company Alteration',
    icon: '🏛️',
    category: 'Company',
    tags: ['Company'],
    fee: 7500,
    processingDays: '5-7 Working Days',
    description: 'Change in Company Name, Registered Office State, or Capital Increase.',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['EGM Notice & Resolution', 'Form SH-7 / INC-22/24', 'Altered MOA/AOA Filing'],
  },
  {
    id: 'dir-3-kyc',
    name: 'DIR-3 KYC',
    icon: '👤',
    category: 'Company',
    tags: ['Popular', 'Company', 'Filing'],
    fee: 1200,
    processingDays: '1 Working Day',
    description: 'Annual mandatory Director KYC filing to keep DIN active on MCA portal.',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['DIR-3 KYC Web/e-Form', 'OTP Verification', 'MCA Active Status Restoration'],
  },
  {
    id: 'roc-efiling',
    name: 'ROC E-Filing',
    icon: '📂',
    category: 'Company',
    tags: ['Company', 'Filing'],
    fee: 6500,
    processingDays: '3-5 Working Days',
    description: 'Annual RoC Compliances: Form AOC-4 (Financials) and MGT-7 (Annual Return).',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['AOC-4 Financials Filing', 'MGT-7 Annual Return', 'Director Report Drafting'],
  },
  {
    id: 'din-registration',
    name: 'DIN Registration',
    icon: '🪪',
    category: 'Company',
    tags: ['Company', 'Registration'],
    fee: 2200,
    processingDays: '2-3 Working Days',
    description: 'New Director Identification Number (DIN) allotment or formal DIN surrender.',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['Form SPICe+ / DIR-3 / DIR-5', 'Identity Attestation', 'Approved DIN Letter'],
  },

  // Food & Trade Licenses
  {
    id: 'fssai-license',
    name: 'FSSAI (Basic/State/Central)',
    icon: '🍽️',
    category: 'Registration',
    tags: ['Popular', 'Registration'],
    fee: 2500,
    processingDays: '3-7 Working Days',
    description: 'FSSAI Food License / Registration via FoSCoS portal with 1-5 yr validity.',
    targetScreen: 'FSSAIEligibility',
    whatsIncluded: ['FoSCoS Filing', 'KOB Classification', '14-Digit License Certificate'],
  },
  {
    id: 'iec-registration',
    name: 'IEC Registration',
    icon: '🌐',
    category: 'Registration',
    tags: ['Popular', 'Registration'],
    fee: 3000,
    processingDays: '2-3 Working Days',
    description: 'DGFT 10-digit Import Export Code registration for global trade.',
    targetScreen: 'IECApplicantType',
    whatsIncluded: ['10-digit DGFT Code', 'Digital Certificate', 'PFMS Bank Validation', 'ICEGATE Linking'],
  },
  {
    id: 'trademark-registration',
    name: 'Trademark Registration',
    icon: '™️',
    category: 'Registration',
    tags: ['Popular', 'Registration'],
    fee: 6500,
    processingDays: '1-2 Working Days',
    description: 'Form TM-A brand name & logo filing with NICE classification & TM report.',
    targetScreen: 'TMApplicantType',
    whatsIncluded: ['TM Search & Report', 'Form TM-A Filing', 'Immediate ™ Usage Rights', 'Govt Tracking'],
  },
  {
    id: 'dsc-service',
    name: 'DSC (Digital Signature)',
    icon: '🔐',
    category: 'Registration',
    tags: ['Popular', 'Registration'],
    fee: 2000,
    processingDays: '1 Working Day',
    description: 'Class 3 Signing + Encryption Digital Signature with USB cryptographic Token.',
    targetScreen: 'Pricing',
    pricingServiceId: 'dsc',
    whatsIncluded: ['Class 3 Sign + Encrypt', 'FIPS Hardware USB Token', 'Paperless Video KYC', '2 Yrs Validity'],
  },
  {
    id: 'msme-udyam',
    name: 'MSME / Udyam',
    icon: '🏭',
    category: 'Registration',
    tags: ['Popular', 'Registration'],
    fee: 2000,
    processingDays: '1-2 Working Days',
    description: 'National MSME / Udyam registration for priority sector lending & subsidies.',
    targetScreen: 'UdyamAadhaar',
    whatsIncluded: ['Official Udyam Certificate', 'MSME Registration Number', 'NIC 5-digit Classification'],
  },
  {
    id: 'tan-registration',
    name: 'TAN Registration',
    icon: '💼',
    category: 'Registration',
    tags: ['Registration', 'Filing'],
    fee: 1500,
    processingDays: '2-3 Working Days',
    description: 'Tax Deduction Account Number (Form 49B) for deducting TDS/TCS.',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['Form 49B Submission', '10-Digit Alpha-Numeric TAN', 'Allotment Letter'],
  },
  {
    id: 'gem-registration',
    name: 'GEM Registration',
    icon: '🏛️',
    category: 'Registration',
    tags: ['Registration'],
    fee: 3500,
    processingDays: '3-5 Working Days',
    description: 'Government e-Marketplace vendor seller onboarding and catalogue listing.',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['Primary Seller Profile', 'OEM / Reseller Assessment', 'Caution Money Assistance'],
  },
  {
    id: 'shop-registration',
    name: 'Shop Registration',
    icon: '🏪',
    category: 'Registration',
    tags: ['Registration'],
    fee: 2500,
    processingDays: '3-5 Working Days',
    description: 'State Shop & Commercial Establishment Act License (Gumasta / Trade License).',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['Municipal Registration', 'Govt Certificate Copy', 'Compliance Display Board'],
  },
  {
    id: 'proprietorship-registration',
    name: 'Proprietorship Registration',
    icon: '👤',
    category: 'Registration',
    tags: ['Registration'],
    fee: 3000,
    processingDays: '2-3 Working Days',
    description: 'Complete sole proprietorship starter pack (GST, Udyam, Current A/c Resolution).',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['MSME / Udyam Certificate', 'GSTIN Registration', 'Bank Current A/c Kit'],
  },
  {
    id: 'partnership-registration',
    name: 'Partnership Registration',
    icon: '🤝',
    category: 'Registration',
    tags: ['Registration'],
    fee: 5000,
    processingDays: '5-7 Working Days',
    description: 'Partnership deed legal drafting, stamp duty execution and RoF registration.',
    targetScreen: 'ServiceDetail',
    whatsIncluded: ['Custom Deed Drafting', 'Stamp Duty Execution', 'Firm PAN & TAN Allotment'],
  },
  {
    id: 'iso-registration',
    name: 'ISO Registration',
    icon: '🏅',
    category: 'Registration',
    tags: ['Registration'],
    fee: 4500,
    processingDays: '3-5 Working Days',
    description: 'ISO 9001:2015 / 45001:2018 Quality Management System certification.',
    targetScreen: 'Pricing',
    pricingServiceId: 'iso',
    whatsIncluded: ['IAF / Non-IAF Certificate', 'Audit Manual & Checklist', 'Verifiable QR Code'],
  },
  {
    id: 'challan-payment',
    name: 'Challan Payment',
    icon: '💰',
    category: 'Filing',
    tags: ['Filing'],
    fee: 1000,
    processingDays: 'Same Day',
    description: 'PAN-Aadhaar Link Penalty Challan & DPIIT Startup recognition.',
    targetScreen: 'Pricing',
    pricingServiceId: 'challan',
    whatsIncluded: ['Challan 280 / e-Pay Tax Filing', 'IT Portal Settlement', 'Status Verification Ack'],
  },
];

// =========================================================================
// TAB 2: 5 FULL-WIDTH INSURANCE SERVICES (PROFIN)
// =========================================================================
export const INSURANCE_SERVICES_LIST = [
  {
    id: 'two-wheeler-insurance',
    title: 'Two Wheeler Insurance',
    subtitle: 'Comprehensive & Third Party cover for bikes and scooters',
    icon: '🛵',
    startingPrice: 'Starting ₹549/yr',
    tag: 'Instant Policy • No Inspection',
    badge: 'Popular',
    link: 'https://profin.gstsuvidhakendra.org.in',
    highlights: ['Zero Inspection Policy', 'Cashless Garage Network', 'Personal Accident Cover ₹15L'],
  },
  {
    id: 'car-insurance',
    title: 'Car Insurance',
    subtitle: 'Protect your car against accidents, theft & natural damages',
    icon: '🚗',
    startingPrice: 'Starting ₹2,094/yr',
    tag: 'Zero Dep • 24x7 Roadside',
    badge: 'Best Value',
    link: 'https://profin.gstsuvidhakendra.org.in',
    highlights: ['Zero Depreciation Add-on', '24x7 Roadside Assistance', 'Engine & Gearbox Protection'],
  },
  {
    id: 'health-insurance',
    title: 'Health Insurance',
    subtitle: 'Cashless medical treatment for individuals and families',
    icon: '🩺',
    startingPrice: 'Starting ₹450/mo',
    tag: '10,000+ Cashless Hospitals',
    badge: 'Essential',
    link: 'https://profin.gstsuvidhakendra.org.in',
    highlights: ['₹5L to ₹1Cr Sum Insured', 'No Pre-policy Medical Test', 'Tax Saving under 80D up to ₹75k'],
  },
  {
    id: 'term-life-insurance',
    title: 'Term Life Insurance',
    subtitle: 'Pure risk protection cover to secure your family future',
    icon: '☂️',
    startingPrice: 'Starting ₹490/mo',
    tag: '₹1 Crore Life Cover',
    badge: 'Tax Saver',
    link: 'https://profin.gstsuvidhakendra.org.in',
    highlights: ['₹1 Crore Cover @ ₹16/day', 'Critical Illness Benefit', 'Tax Free Payout under 10(10D)'],
  },
  {
    id: 'investment-plans',
    title: 'Investment Plans',
    subtitle: 'Guaranteed returns, ULIPs & child wealth creation plans',
    icon: '📈',
    startingPrice: 'Returns up to 15%',
    tag: 'Guaranteed Returns + Life Cover',
    badge: 'High Growth',
    link: 'https://profin.gstsuvidhakendra.org.in',
    highlights: ['Guaranteed Annual Payouts', 'Market Linked High Growth', 'Capital Protection Shield'],
  },
];

// =========================================================================
// TAB 3: 10 MARKETING SERVICES
// =========================================================================
export const MARKETING_SERVICES_LIST = [
  {
    id: 'mkt-social-media',
    title: 'Social Media Marketing',
    icon: '📱',
    color: '#EC4899',
    bgColor: '#FDF2F8',
    description: 'Instagram, Facebook & LinkedIn page growth, content creation & reels.',
    features: ['Monthly 12-20 Creative Posts', 'Reels & Story Management', 'Organic Follower Engagement'],
    price: '₹4,999/mo',
  },
  {
    id: 'mkt-google-ads',
    title: 'Google Ads / PPC',
    icon: '🎯',
    color: '#3B82F6',
    bgColor: '#EFF6FF',
    description: 'Targeted Google search, display & shopping ads for high-intent customer leads.',
    features: ['Keyword ROI Optimization', 'Ad Copy & Landing Page', 'Weekly Conversion Reports'],
    price: '₹6,999/mo',
  },
  {
    id: 'mkt-seo',
    title: 'SEO Services',
    icon: '🔍',
    color: '#10B981',
    bgColor: '#ECFDF5',
    description: 'On-page, technical & off-page SEO to rank #1 on Google searches.',
    features: ['Keyword Ranking Guarantee', 'Google Core Web Vitals Fix', 'High Authority Backlinks'],
    price: '₹7,999/mo',
  },
  {
    id: 'mkt-logo-branding',
    title: 'Logo & Branding',
    icon: '🎨',
    color: '#8B5CF6',
    bgColor: '#F5F3FF',
    description: 'Complete brand identity design, vector logos, color palette & style book.',
    features: ['3 Unique Logo Concepts', 'Full Vector HD Files (AI/PNG)', 'Brand Typography Guide'],
    price: '₹2,499',
  },
  {
    id: 'mkt-business-card',
    title: 'Business Card Design',
    icon: '📇',
    color: '#F59E0B',
    bgColor: '#FEF3C7',
    description: 'Premium visiting cards with interactive QR code for digital contact save.',
    features: ['Print-Ready 300DPI Files', 'Dynamic QR Code Embedded', 'Front & Back Luxury Layout'],
    price: '₹799',
  },
  {
    id: 'mkt-pamphlet-brochure',
    title: 'Pamphlet / Brochure',
    icon: '📑',
    color: '#EF4444',
    bgColor: '#FEF2F2',
    description: 'Corporate tri-fold brochures, product flyers and event promo collateral.',
    features: ['Custom Visual Graphics', 'Product Catalogue Layout', 'Digital PDF & Print Formats'],
    price: '₹1,499',
  },
  {
    id: 'mkt-video-marketing',
    title: 'Video Marketing',
    icon: '🎥',
    color: '#6366F1',
    bgColor: '#EEF2FF',
    description: '2D animation explainers, brand promotional videos and social media reels.',
    features: ['Professional Scriptwriting', 'Studio Voiceover Included', 'Full HD 1080p Export'],
    price: '₹3,499',
  },
  {
    id: 'mkt-whatsapp-marketing',
    title: 'WhatsApp Marketing',
    icon: '💬',
    color: '#25D366',
    bgColor: '#F0FDF4',
    description: 'Meta verified WhatsApp API setup, automated chatbots & bulk campaigns.',
    features: ['Green Tick Assistance', 'High Delivery Inbox Rate', 'Automated Lead Capture Bot'],
    price: '₹2,999',
  },
  {
    id: 'mkt-email-marketing',
    title: 'Email Marketing',
    icon: '✉️',
    color: '#14B8A6',
    bgColor: '#F0FDFA',
    description: 'High-converting newsletters, customer onboarding drips & offer campaigns.',
    features: ['Responsive HTML Templates', 'Spam Score Optimization', 'Subscriber List Hygiene'],
    price: '₹2,499',
  },
  {
    id: 'mkt-google-my-business',
    title: 'Google My Business',
    icon: '📍',
    color: '#F97316',
    bgColor: '#FFF7ED',
    description: 'GMB profile setup, verification, local SEO and Google Maps ranking.',
    features: ['Instant Map Pin Verification', '5-Star Review Generation Strategy', 'Local Citation Building'],
    price: '₹1,999',
  },
];

// =========================================================================
// TAB 4: 8 WEB & DIGITAL SERVICES
// =========================================================================
export const WEB_SERVICES_LIST = [
  {
    id: 'web-development',
    title: 'Website Development',
    icon: '💻',
    color: '#1B2B5E',
    bgColor: '#F1F5F9',
    priceRange: '₹9,999 - ₹24,999',
    description: 'Responsive business websites, custom web apps and corporate portals.',
    deliverables: ['Mobile & SEO Friendly', 'Fast NVMe Hosting Setup', 'Admin Content CMS', 'Free SSL & Domain'],
  },
  {
    id: 'app-development',
    title: 'App Development',
    icon: '📱',
    color: '#0284C7',
    bgColor: '#E0F2FE',
    priceRange: '₹24,999 - ₹74,999',
    description: 'Native & cross-platform Android and iOS apps using modern stacks.',
    deliverables: ['Google Play & App Store Release', 'Push Notifications & Auth', 'Realtime Backend APIs'],
  },
  {
    id: 'domain-hosting',
    title: 'Domain & Hosting',
    icon: '🌐',
    color: '#059669',
    bgColor: '#ECFDF5',
    priceRange: '₹1,499 / year',
    description: '.com / .in domain registration with enterprise SSD cloud server hosting.',
    deliverables: ['99.9% Server Uptime', 'Unlimited Free SSL Certificates', 'Daily Automated Backups'],
  },
  {
    id: 'google-workspace',
    title: 'Google Workspace',
    icon: '✉️',
    color: '#EA4335',
    bgColor: '#FEF2F2',
    priceRange: '₹250 / user / mo',
    description: 'Official corporate business emails (name@yourcompany.com) with Gmail.',
    deliverables: ['30 GB Cloud Storage', 'Google Meet & Drive Suite', 'Admin Security Controls'],
  },
  {
    id: 'software-development',
    title: 'Software Development',
    icon: '⚡',
    color: '#7C3AED',
    bgColor: '#F5F3FF',
    priceRange: '₹19,999 onwards',
    description: 'Custom Billing, CRM, Inventory & ERP management software solutions.',
    deliverables: ['Tailored Workflow Logic', 'GST Invoice Generation', 'Role-Based Access Control'],
  },
  {
    id: 'ecommerce-setup',
    title: 'E-commerce Setup',
    icon: '🛍️',
    color: '#D97706',
    bgColor: '#FFFBEB',
    priceRange: '₹14,999 onwards',
    description: 'Complete online store setup with Shopify, WooCommerce & payment gateway.',
    deliverables: ['Catalog & Inventory Sync', 'Payment & Shipping Integration', 'Abandoned Cart Recovery'],
  },
  {
    id: 'payment-gateway',
    title: 'Payment Gateway Integration',
    icon: '💳',
    color: '#2563EB',
    bgColor: '#EFF6FF',
    priceRange: '₹2,999',
    description: 'Razorpay, Paytm, Cashfree & PhonePe merchant gateway onboarding.',
    deliverables: ['Instant UPI, Card & Netbanking', 'Fast Settlement Setup', 'Zero Maintenance Setup'],
  },
  {
    id: 'digital-visiting-card',
    title: 'Digital Visiting Card',
    icon: '📲',
    color: '#0D9488',
    bgColor: '#F0FDFA',
    priceRange: '₹999',
    description: 'Interactive smart QR & NFC-enabled digital business card for mobile sharing.',
    deliverables: ['One-Tap WhatsApp & Call', 'Social Links & Product Showcase', 'Update Anytime Live'],
  },
];

// =========================================================================
// Category 12: 13 Downloadable Legal Formats
// =========================================================================
export const REQUIRED_FORMATS = [
  {
    id: 'format-noc',
    name: 'No Objection Certificate (NOC)',
    description: 'Standard Landlord / Owner NOC format for business address registration.',
    category: 'Property & Premises',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-noc-blood-rel',
    name: 'NOC for Blood Relative',
    description: 'NOC when premises is owned by Father, Mother, Spouse or Brother without rent.',
    category: 'Property & Premises',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-gst-auth-sig',
    name: 'GST Declaration for Authorised Signatory',
    description: 'Mandatory declaration format to appoint primary authorized signatory for GST.',
    category: 'GST Compliance',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-auth-letter',
    name: 'Authorisation Letter Format',
    description: 'General authority letter for regulatory departments, banks and tax authorities.',
    category: 'Corporate Legal',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-gst-board-res',
    name: 'GST Board Resolutions',
    description: 'Specimen board resolution for companies applying for GST registration.',
    category: 'GST Compliance',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-partnership-deed',
    name: 'Partnership Deed Format',
    description: 'Comprehensive legal draft covering profit-sharing, capital and dissolution clauses.',
    category: 'Partnership & LLP',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-rent-agreement-gst',
    name: 'Rent Agreement Format for GST Registration',
    description: 'Customized commercial lease agreement format fulfilling GST dept criteria.',
    category: 'Property & Premises',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-rent-free-noc',
    name: 'Rent Agreement Free NOC',
    description: 'Consent letter for operating trade without commercial rent agreement.',
    category: 'Property & Premises',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-fssai-decl',
    name: 'Declaration for Application Form for FSSAI Reg',
    description: 'Mandatory annexure declaration form required for FoSCoS food license issuance.',
    category: 'Food & FSSAI',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-dir-2',
    name: 'DIR-2 (Consent to Act as Director)',
    description: 'Form DIR-2 consent letter pursuant to Section 152(5) of Companies Act, 2013.',
    category: 'MCA & RoC',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-name-approval',
    name: 'Name Approval Format (RUN / SPICe+)',
    description: 'Format for main industrial objects and trademark no-objection for company name approval.',
    category: 'MCA & RoC',
    fileType: 'MCA / RoC',
  },
  {
    id: 'format-inc-9',
    name: 'INC-9 (Declaration by First Subscriber/Director)',
    description: 'Mandatory electronic INC-9 declaration format for new company incorporation.',
    category: 'MCA & RoC',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-dsc-board-res',
    name: 'Template-Board-Resolution for DSC',
    description: 'Board resolution format authorized by company to apply for Organization DSC.',
    category: 'Digital Signature',
    fileType: 'PDF / DOC',
  },
];

// =========================================================================
// Backward Compatible Exports
// =========================================================================
export const CATEGORIES = [];
export const DIRECT_SERVICES = [];
export const FINANCIAL_SERVICES = {
  profinUrl: 'https://profin.gstsuvidhakendra.org.in',
  categories: [
    {
      id: 'insurance',
      title: 'Insurance',
      icon: '🛡️',
      badge: '5 options',
      items: [
        { id: 'two_wheeler_ins', name: 'Two Wheeler Insurance', partner: 'ProFin', type: 'insurance' },
        { id: 'car_ins', name: 'Car Insurance', partner: 'ProFin', type: 'insurance' },
        { id: 'health_ins', name: 'Health Insurance', partner: 'ProFin', type: 'insurance' },
        { id: 'term_life_ins', name: 'Term Life Insurance', partner: 'ProFin', type: 'insurance' },
        { id: 'investment_ins', name: 'Investment', partner: 'ProFin', type: 'insurance' },
      ],
    },
  ],
};
