/** GST state codes ke saath saare states + UTs (dropdown ke liye) */
export const INDIAN_STATES = [
  { id: '35', label: 'Andaman & Nicobar Islands' },
  { id: '37', label: 'Andhra Pradesh' },
  { id: '12', label: 'Arunachal Pradesh' },
  { id: '18', label: 'Assam' },
  { id: '10', label: 'Bihar' },
  { id: '04', label: 'Chandigarh' },
  { id: '22', label: 'Chhattisgarh' },
  { id: '26', label: 'Dadra & Nagar Haveli and Daman & Diu' },
  { id: '07', label: 'Delhi' },
  { id: '30', label: 'Goa' },
  { id: '24', label: 'Gujarat' },
  { id: '06', label: 'Haryana' },
  { id: '02', label: 'Himachal Pradesh' },
  { id: '01', label: 'Jammu & Kashmir' },
  { id: '20', label: 'Jharkhand' },
  { id: '29', label: 'Karnataka' },
  { id: '32', label: 'Kerala' },
  { id: '38', label: 'Ladakh' },
  { id: '31', label: 'Lakshadweep' },
  { id: '23', label: 'Madhya Pradesh' },
  { id: '27', label: 'Maharashtra' },
  { id: '14', label: 'Manipur' },
  { id: '17', label: 'Meghalaya' },
  { id: '15', label: 'Mizoram' },
  { id: '13', label: 'Nagaland' },
  { id: '21', label: 'Odisha' },
  { id: '34', label: 'Puducherry' },
  { id: '03', label: 'Punjab' },
  { id: '08', label: 'Rajasthan' },
  { id: '11', label: 'Sikkim' },
  { id: '33', label: 'Tamil Nadu' },
  { id: '36', label: 'Telangana' },
  { id: '16', label: 'Tripura' },
  { id: '09', label: 'Uttar Pradesh' },
  { id: '05', label: 'Uttarakhand' },
  { id: '19', label: 'West Bengal' },
];

export const getStateByCode = (code) =>
  INDIAN_STATES.find((s) => s.id === code) || null;
