/**
 * Central Configuration for All Business, Tax, Legal & Compliance Services
 * Used in My Work Services Hub, Pricing Screens, and Sub-item navigations.
 */

export const CATEGORIES = [
  {
    id: 'gst-services',
    title: 'GST Services',
    icon: '📋',
    badge: '10 services',
    description: 'Registration, Monthly/Quarterly Returns, LUT & Notice Management',
    subItems: [
      {
        id: 'gst-registration',
        name: 'GST Registration',
        description: 'New GST Registration for Proprietorship, Partnership, LLP or Company.',
        fee: 10000,
        processingDays: '3-5 Working Days',
        targetScreen: 'GSTConstitution',
        whatsIncluded: ['GSTIN Allotment', 'GST Certificate', 'HSN Mapping', 'Govt Portal Filing'],
      },
      {
        id: 'gst-returns',
        name: 'GST Returns',
        description: 'Monthly & quarterly GSTR-1, GSTR-3B and GSTR-9 annual return filings.',
        fee: 1500,
        processingDays: '1-2 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['GSTR-1 & 3B Filing', 'Input Tax Credit (ITC) Check', 'Tax Challan Support'],
      },
      {
        id: 'gst-revocation',
        name: 'Revocation of Cancellation',
        description: 'Revoke and restore cancelled GSTIN from jurisdictional tax department.',
        fee: 3500,
        processingDays: '7-10 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['Dept Application Filing', 'Show Cause Notice Reply', 'Officer Liaisoning'],
      },
      {
        id: 'gst-notice-response',
        name: 'Response of Notice',
        description: 'Professional legal drafting and reply submission for ASMT-10, DRC-01 notices.',
        fee: 3000,
        processingDays: '3-5 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['Notice Scrutiny', 'Legal Reply Drafting', 'Portal Submission & Hearing Prep'],
      },
      {
        id: 'gst-amendment',
        name: 'Amendment and Correction',
        description: 'Core and non-core field modifications (Address, Director, HSN, Bank).',
        fee: 2000,
        processingDays: '2-4 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['Core / Non-Core Amendment', 'Document Verification', 'Updated Certificate'],
      },
      {
        id: 'gst-lut',
        name: 'GST LUT Filing',
        description: 'Letter of Undertaking (LUT) for zero-rated export of goods and services.',
        fee: 1500,
        processingDays: '1 Working Day',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['Form RFD-11 LUT Filing', 'Annual Validity ARN', 'Zero-Duty Export Eligibility'],
      },
      {
        id: 'gst-surrender',
        name: 'GST Surrender',
        description: 'Formal application for closure and surrender of inactive/defunct GSTIN.',
        fee: 2500,
        processingDays: '5-7 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['Final GSTR-10 Return', 'Cancellation Order Application', 'No-Dues Clearance'],
      },
      {
        id: 'gst-reconciliation',
        name: 'GST Reconciliation',
        description: 'Reconciliation of GSTR-2B with Purchase Register (Books vs Portal).',
        fee: 2500,
        processingDays: '2-3 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['GSTR-2B vs Books Report', 'Mismatched Invoices Flagging', 'ITC Maximization'],
      },
      {
        id: 'gst-pmt-09',
        name: 'GST PMT-09',
        description: 'Transfer misallocated cash ledger balances between CGST, SGST, IGST heads.',
        fee: 1200,
        processingDays: '1 Working Day',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['Cash Ledger Balance Transfer', 'Form PMT-09 E-Filing', 'Instant Ledger Adjustment'],
      },
      {
        id: 'gst-eway-bill',
        name: 'E-way Bill',
        description: 'E-way bill generation and system setup for inter-state & intra-state consignments.',
        fee: 1000,
        processingDays: 'Same Day',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['Part A & Part B Generation', 'Consolidated E-way Bill', 'Transporter Mapping'],
      },
    ],
  },
  {
    id: 'accounting-taxation',
    title: 'Accounting & Taxation',
    icon: '📊',
    badge: '4 services',
    description: 'Income Tax, TDS Returns, Balance Sheets & Monthly Bookkeeping',
    subItems: [
      {
        id: 'tds-return',
        name: 'TDS Return Filing',
        description: 'Quarterly Form 24Q, 26Q, 27Q filings and Form 16/16A certificate generation.',
        fee: 2500,
        processingDays: '2-3 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['FVU File Preparation', 'TRACES Upload', 'Form 16/16A Generation'],
      },
      {
        id: 'itr-filing',
        name: 'Income Tax Return (ITR) & Audit',
        description: 'Annual ITR filing for individuals, businesses, professionals & Section 44AB audits.',
        fee: 3000,
        processingDays: '2-3 Working Days',
        targetScreen: 'ITRProfile',
        whatsIncluded: ['ITR-1/2/3/4 Filing', 'Computation Sheet', 'AIS/26AS Match', 'ITR-V Ack'],
      },
      {
        id: 'monthly-accounting',
        name: 'Accounting & Taxation',
        description: 'Monthly Tally/Zoho ledger maintenance, bank reconciliation and compliance tracking.',
        fee: 5000,
        processingDays: 'Monthly Retainer',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['Double-Entry Bookkeeping', 'Monthly P&L & Balance Sheet', 'Tax Compliance Review'],
      },
      {
        id: 'balance-sheet',
        name: 'Balance Sheet',
        description: 'Audited Financial Statements, CMA Preparation & CA certified balance sheets.',
        fee: 6000,
        processingDays: '3-5 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['CA Certified Balance Sheet', 'Profit & Loss Statement', 'Notes to Accounts'],
      },
    ],
  },
  {
    id: 'company-compliances',
    title: 'Company Registration & Compliances',
    icon: '🏢',
    badge: '11 services',
    description: 'MCA Incorportion, RoC E-Filings, DIN, DIR-3 KYC & Amendments',
    subItems: [
      {
        id: 'company-registration',
        name: 'Company Registration / KYC',
        description: 'Private Limited, OPC or LLP incorporation with MCA SPICe+ and AGILE-PRO.',
        fee: 15000,
        processingDays: '7-10 Working Days',
        targetScreen: 'PLCApplicant',
        whatsIncluded: ['COI (Incorporation Cert)', 'PAN, TAN & 2 DINs', 'MOA & AOA Drafting', 'Name Approval'],
      },
      {
        id: 'company-closing',
        name: 'Company Closing',
        description: 'Strike off defunct company via Form STK-2 fast track exit route.',
        fee: 12000,
        processingDays: '15-20 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['Form STK-2 Preparation', 'Indemnity Bond & Affidavits', 'RoC Strike-off Order'],
      },
      {
        id: 'company-conversion',
        name: 'Conversion of Company',
        description: 'Conversion from Partnership to LLP, OPC to Pvt Ltd, or Pvt Ltd to Public Ltd.',
        fee: 14000,
        processingDays: '10-14 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['Special Resolution Drafting', 'Form MGT-14 & INC-6/18', 'Fresh Certificate of Inc'],
      },
      {
        id: 'company-alteration',
        name: 'Company Alteration',
        description: 'Change in Company Name, Registered Office State, or Authorized Capital Increase.',
        fee: 7500,
        processingDays: '5-7 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['EGM Notice & Resolution', 'Form SH-7 / INC-22/24', 'Altered MOA/AOA Filing'],
      },
      {
        id: 'dir-3-kyc',
        name: 'DIR-3 KYC / Filing',
        description: 'Annual mandatory Director KYC filing to keep DIN active on MCA portal.',
        fee: 1200,
        processingDays: '1 Working Day',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['DIR-3 KYC Web/e-Form', 'OTP Verification', 'MCA Active Status Restoration'],
      },
      {
        id: 'company-amendments',
        name: 'Amendments / Correction',
        description: 'Addition/Removal of Director (DIR-12), Resignation and Partner changes.',
        fee: 3500,
        processingDays: '3-5 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['Board Resolution & Consent DIR-2', 'Form DIR-12 E-Filing', 'RoC Master Data Update'],
      },
      {
        id: 'form-20a',
        name: 'FORM-20A',
        description: 'Commencement of Business declaration (mandatory within 180 days of inc).',
        fee: 2500,
        processingDays: '2 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['Bank Proof Verification', 'Form INC-20A E-Filing', 'RoC Approval SRN'],
      },
      {
        id: 'cma-report',
        name: 'CMA Report',
        description: 'Credit Monitoring Arrangement data preparation for Bank loans & working capital.',
        fee: 5500,
        processingDays: '3-4 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['7-Year Financial Projections', 'MPBF Working & Ratio Analysis', 'Bank Loan CMA Pack'],
      },
      {
        id: 'form-adt-1',
        name: 'Form ADT-1',
        description: 'Appointment or resignation of Statutory Auditor with the Registrar of Companies.',
        fee: 2500,
        processingDays: '2-3 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['Auditor Consent & Eligibility', 'Form ADT-1 E-Filing', 'MCA SRN Generation'],
      },
      {
        id: 'roc-efiling',
        name: 'ROC E-Filing',
        description: 'Annual RoC Compliances: Form AOC-4 (Financials) and MGT-7 (Annual Return).',
        fee: 6500,
        processingDays: '3-5 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['AOC-4 Financials Filing', 'MGT-7 Annual Return', 'Director Report Drafting'],
      },
      {
        id: 'din-services',
        name: 'DIN (Registration / Surrender)',
        description: 'New Director Identification Number (DIN) allotment or formal DIN surrender.',
        fee: 2200,
        processingDays: '2-3 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['Form SPICe+ / DIR-3 / DIR-5', 'Identity Attestation', 'Approved DIN Letter'],
      },
    ],
  },
  {
    id: 'fssai-services',
    title: 'FSSAI (Food License)',
    icon: '🍽️',
    badge: '3 services',
    description: 'Basic Registration, State & Central Licenses via FoSCoS Portal',
    subItems: [
      {
        id: 'fssai-basic',
        name: 'Basic Registration',
        description: 'For small food businesses, hawkers, petty retailers with turnover under ₹12 Lakhs.',
        fee: 2500,
        processingDays: '3-5 Working Days',
        targetScreen: 'FSSAIEligibility',
        whatsIncluded: ['1-5 Year Validity Option', 'FoSCoS Form A Filing', '14-Digit Registration No.'],
      },
      {
        id: 'fssai-state',
        name: 'State License',
        description: 'For medium manufacturers, restaurants, distributors with turnover ₹12L to ₹20 Cr.',
        fee: 5500,
        processingDays: '7-12 Working Days',
        targetScreen: 'FSSAIEligibility',
        whatsIncluded: ['Form B State License', 'KOB Classification', 'Sanitary Inspection Support'],
      },
      {
        id: 'fssai-central',
        name: 'Central License',
        description: 'For large manufacturers, importers, exporters, e-commerce & multi-state chains.',
        fee: 9500,
        processingDays: '15-20 Working Days',
        targetScreen: 'FSSAIEligibility',
        whatsIncluded: ['Central FoSCoS License', 'Import-Export Tagging', 'DGFT & Customs Alignment'],
      },
    ],
  },
  {
    id: 'other-registration',
    title: 'Other Registration',
    icon: '📄',
    badge: '5 services',
    description: 'TAN, GEM, Shop Act, Partnerships & Trade Registrations',
    subItems: [
      {
        id: 'tan-registration',
        name: 'TAN Registration',
        description: 'Tax Deduction and Collection Account Number (Form 49B) for deducting TDS/TCS.',
        fee: 1500,
        processingDays: '2-3 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['Form 49B Submission', '10-Digit Alpha-Numeric TAN', 'Allotment Letter'],
      },
      {
        id: 'gem-registration',
        name: 'GEM Registration',
        description: 'Government e-Marketplace vendor seller onboarding and catalogue listing.',
        fee: 3500,
        processingDays: '3-5 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['Primary Seller Profile', 'OEM / Reseller Assessment', 'Caution Money Assistance'],
      },
      {
        id: 'shop-registration',
        name: 'Shop Registration',
        description: 'State Shop & Commercial Establishment Act License (Gumasta / Trade License).',
        fee: 2500,
        processingDays: '3-5 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['Municipal Registration', 'Govt Certificate Copy', 'Compliance Display Board'],
      },
      {
        id: 'proprietorship-registration',
        name: 'Proprietorship Registration',
        description: 'Complete sole proprietorship starter pack (GST, Udyam, Current A/c Resolution).',
        fee: 3000,
        processingDays: '2-3 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['MSME / Udyam Certificate', 'GSTIN Registration', 'Bank Current A/c Kit'],
      },
      {
        id: 'partnership-registration',
        name: 'Partnership Registration',
        description: 'Partnership deed legal drafting, stamp duty execution and Registrar of Firms (RoF).',
        fee: 5000,
        processingDays: '5-7 Working Days',
        targetScreen: 'ServiceDetail',
        whatsIncluded: ['Custom Deed Drafting', 'Stamp Duty Execution', 'Firm PAN & TAN Allotment'],
      },
    ],
  },
];

/**
 * Direct Service Cards (Tap directly opens Pricing Screen with multiple plans)
 */
export const DIRECT_SERVICES = [
  {
    id: 'iec',
    title: 'IEC (Import Export Code)',
    icon: '🌐',
    badge: '4 plans',
    subtitle: 'DGFT 10-digit Import Export License for global trade',
    targetForm: 'IECApplicantType',
    plans: [
      {
        id: 'iec-company',
        name: 'Company Plan',
        price: 4000,
        description: 'For Private Limited, Public Limited & LLP entities trading globally.',
        processingDays: '3–5 Working Days',
        whatsIncluded: ['10-digit DGFT Code', 'IEC Certificate', 'PFMS Bank Pre-validation', 'Customs ICEGATE Linking'],
      },
      {
        id: 'iec-partnership',
        name: 'Partnership Plan',
        price: 3500,
        description: 'For Registered & Unregistered Partnership firms with export intent.',
        processingDays: '3–5 Working Days',
        whatsIncluded: ['DGFT e-IEC Allotment', 'Digital Certificate', 'PFMS Validation', 'Directorate Support'],
      },
      {
        id: 'iec-proprietorship',
        name: 'Proprietorship Plan',
        price: 3000,
        description: 'For Individual & Sole Proprietor merchant exporters.',
        processingDays: '2–3 Working Days',
        whatsIncluded: ['Individual IEC Allotment', 'Online Certificate Copy', 'Bank Account Verification'],
      },
      {
        id: 'iec-amendment',
        name: 'IEC Amendment / Update',
        description: 'Annual mandatory IEC renewal or updating address, partners, bank accounts.',
        price: 1500,
        processingDays: '1–2 Working Days',
        whatsIncluded: ['DGFT Annual Validation', 'Branch / Director Updates', 'Updated Certificate Copy'],
      },
    ],
  },
  {
    id: 'trademark',
    title: 'Trademark',
    icon: '™️',
    badge: '9 plans',
    subtitle: 'IP India Brand Protection, TM Registration, Objections & Hearings',
    targetForm: 'TMApplicantType',
    plans: [
      {
        id: 'tm-registration',
        name: 'Trademark Registration',
        price: 6500,
        description: 'Comprehensive Form TM-A brand name & logo filing with NICE classification.',
        processingDays: '1–2 Working Days',
        whatsIncluded: ['TM Search & Report', 'Form TM-A Filing', 'Immediate ™ Usage Rights', 'Government Portal Tracking'],
      },
      {
        id: 'tm-objection-reply',
        name: 'TM Objection Reply',
        price: 3500,
        description: 'Drafting legal reply to Examination Report under Section 9 & 11.',
        processingDays: '3–5 Working Days',
        whatsIncluded: ['Exam Report Analysis', 'Legal Submissions Drafting', 'Affidavit of Usage & Evidence'],
      },
      {
        id: 'tm-hearing',
        name: 'Hearing Charges',
        price: 4500,
        description: 'Representation by senior Trademark Attorney before the TM Registrar.',
        processingDays: 'On Hearing Date',
        whatsIncluded: ['Senior Attorney Briefing', 'Virtual / Physical Hearing', 'Written Arguments Submission'],
      },
      {
        id: 'tm-objection-filing',
        name: 'Objection Filing',
        price: 3000,
        description: 'Formal objection response filing for pending trademark applications.',
        processingDays: '2–3 Working Days',
        whatsIncluded: ['Legal Draft Preparation', 'Registry Portal Submission', 'Status Tracking'],
      },
      {
        id: 'tm-opposed',
        name: 'Opposed Application Handling',
        price: 5000,
        description: 'Handling Section 21 third-party opposition proceedings in TM journal.',
        processingDays: 'Case Specific',
        whatsIncluded: ['Counter Statement TM-O', 'Rule 45/46 Evidence Filing', 'Case Management'],
      },
      {
        id: 'tm-renewal',
        name: 'TM Renewal',
        price: 8000,
        description: '10-year periodic trademark protection renewal on IP India gateway.',
        processingDays: '3–5 Working Days',
        whatsIncluded: ['Form TM-R Filing', '10-Year Protection Extension', 'Updated Status Allotment'],
      },
      {
        id: 'tm-assignment',
        name: 'TM Assignment',
        price: 5500,
        description: 'Transfer or licensing of trademark ownership with/without goodwill.',
        processingDays: '7–10 Working Days',
        whatsIncluded: ['Assignment Deed Drafting', 'Form TM-P E-Filing', 'New Owner Recordal'],
      },
      {
        id: 'tm-opposition',
        name: 'TM Opposition (Filing)',
        price: 6000,
        description: 'Filing Notice of Opposition against infringing mark published in journal.',
        processingDays: '3–5 Working Days',
        whatsIncluded: ['Notice of Opposition Drafting', 'Journal Cross-Verification', 'Official Registry Filing'],
      },
      {
        id: 'tm-rectification',
        name: 'TM Rectification',
        price: 5000,
        description: 'Removal or correction of wrongly registered / non-used marks from register.',
        processingDays: 'Case Specific',
        whatsIncluded: ['Rectification Petition Drafting', 'Grounds of Non-Use Framing', 'Registry Representation'],
      },
    ],
  },
  {
    id: 'dsc',
    title: 'DSC (Digital Signature)',
    icon: '🔐',
    badge: '13 plans',
    subtitle: 'Class 3 Paperless Digital Signature Certificates with FIPS USB Token',
    targetForm: 'OtherSelectService',
    plans: [
      {
        id: 'dsc-class3-combo-2yr',
        name: 'Class 3 Combo 2yr',
        price: 2500,
        description: 'Sign + Encrypt 2-Year Certificate with Hyp2003 / Proxkey USB Token.',
        processingDays: '1 Working Day',
        whatsIncluded: ['Signing + Encryption Cert', 'FIPS Cryptographic Token', 'Paperless Video KYC', '2 Years Validity'],
      },
      {
        id: 'dsc-class3-combo-3yr',
        name: 'Class 3 Combo 3yr',
        price: 3500,
        description: 'Sign + Encrypt 3-Year Certificate with FIPS Compliant USB Token.',
        processingDays: '1 Working Day',
        whatsIncluded: ['Signing + Encryption Cert', 'FIPS Cryptographic Token', '3 Years Validity', 'Free Delivery'],
      },
      {
        id: 'dsc-ind-sign',
        name: 'Individual Sign Only',
        price: 1200,
        description: 'For Income Tax, GST, MCA Director KYC and document signing.',
        processingDays: 'Same Day',
        whatsIncluded: ['Individual Signing Cert', '2 Years Validity', 'Paperless Issuance'],
      },
      {
        id: 'dsc-ind-encrypt',
        name: 'Individual Encrypt Only',
        price: 1200,
        description: 'Dedicated encryption certificate for secure data & e-tender submissions.',
        processingDays: 'Same Day',
        whatsIncluded: ['Individual Encryption Cert', '2 Years Validity', 'Instant Download'],
      },
      {
        id: 'dsc-ind-combo',
        name: 'Individual Combo',
        price: 2000,
        description: 'Signing + Encryption for personal e-tendering and regulatory filings.',
        processingDays: '1 Working Day',
        whatsIncluded: ['Dual Certificate (Sign + Encrypt)', '2 Years Validity', 'Token Setup Support'],
      },
      {
        id: 'dsc-org-sign',
        name: 'Organisation Sign Only',
        price: 2200,
        description: 'Signing certificate under Organization name (Company, LLP, Firm).',
        processingDays: '1 Working Day',
        whatsIncluded: ['Org Signing Certificate', '2 Years Validity', 'Company Authorization Check'],
      },
      {
        id: 'dsc-org-encrypt',
        name: 'Organisation Encrypt Only',
        price: 2200,
        description: 'Organization encryption certificate for Government e-Procurement.',
        processingDays: '1 Working Day',
        whatsIncluded: ['Org Encryption Certificate', '2 Years Validity', 'Tender Support'],
      },
      {
        id: 'dsc-org-combo',
        name: 'Organisation Combo',
        price: 3800,
        description: 'Complete Sign + Encrypt combo for Company e-Tendering and CPPP.',
        processingDays: '1 Working Day',
        whatsIncluded: ['Org Sign + Encrypt Cert', 'FIPS Cryptographic Token', '2 Years Validity'],
      },
      {
        id: 'dsc-dgft',
        name: 'DGFT DSC',
        price: 2800,
        description: 'Specialized certificate for Import Export Code & DGFT portal filings.',
        processingDays: '1 Working Day',
        whatsIncluded: ['DGFT Specific Format', 'IEC Linked Signature', '2 Years Validity'],
      },
      {
        id: 'dsc-token-only',
        name: 'Token Only',
        price: 800,
        description: 'Standalone Hyp2003 / Watchdata blank hardware cryptographic USB token.',
        processingDays: '2–3 Days Courier',
        whatsIncluded: ['FIPS 140-2 Level 3 Token', 'Plug & Play Drivers', 'Brand New Sealed Unit'],
      },
      {
        id: 'dsc-usb-token',
        name: 'USB Token (ProxKey)',
        price: 950,
        description: 'ProxKey Watchdata USB Token for high performance digital signing.',
        processingDays: '2–3 Days Courier',
        whatsIncluded: ['ProxKey Hardware Token', 'Auto-installation Software', 'Courier Delivery'],
      },
      {
        id: 'dsc-foreign-national',
        name: 'Foreign National DSC',
        price: 6500,
        description: 'For Foreign Directors & Non-Resident Indian (NRI) company stakeholders.',
        processingDays: '2–3 Working Days',
        whatsIncluded: ['Apostille / Embassy Attestation KYC', '2 Years Validity', 'FIPS Hardware Token'],
      },
      {
        id: 'dsc-nri',
        name: 'NRI DSC',
        price: 5500,
        description: 'For Non-Resident Indians with passport verification for MCA & Tax filings.',
        processingDays: '2 Working Days',
        whatsIncluded: ['Passport Video Verification', 'Sign + Encrypt Combo', 'Global Support'],
      },
    ],
  },
  {
    id: 'udyam',
    title: 'MSME / Udyam',
    icon: '🏭',
    badge: '2 plans',
    subtitle: 'National MSME / Udyam Registration & Priority Lending Certificate',
    targetForm: 'UdyamAadhaar',
    plans: [
      {
        id: 'udyam-new-reg',
        name: 'Udyam Registration',
        price: 2000,
        description: 'New government MSME / Udyam registration with lifetime validity & subsidy benefits.',
        processingDays: '1–2 Working Days',
        whatsIncluded: ['Official Udyam Certificate', 'MSME Registration Number', 'NIC 5-digit Classification', 'Priority Sector Lending Eligibility'],
      },
      {
        id: 'udyam-kyc-update',
        name: 'Udyam KYC Update',
        price: 1000,
        description: 'Updating Plant Unit, Address, Bank Account, or Turnover details on Udyam portal.',
        processingDays: '1 Working Day',
        whatsIncluded: ['Udyam Portal Verification', 'Unit Addition / Modification', 'Updated Certificate Download'],
      },
    ],
  },
  {
    id: 'challan',
    title: 'Challan Payment',
    icon: '💰',
    badge: '2 plans',
    subtitle: 'PAN-Aadhaar Linking Penalty Challan & Startup India DPIIT Certification',
    targetForm: 'OtherSelectService',
    plans: [
      {
        id: 'pan-aadhaar-link',
        name: 'PAN-Aadhaar Link',
        price: 1000,
        description: 'Statutory ₹1,000 Section 234H challan generation & linking submission on IT portal.',
        processingDays: 'Same Day',
        whatsIncluded: ['Challan 280 / e-Pay Tax Filing', 'NSDL / ITD Portal Settlement', 'Status Verification Confirmation'],
      },
      {
        id: 'startup-dpiit-reg',
        name: 'Startup / DPIIT Registration',
        price: 3500,
        description: 'Official Department for Promotion of Industry and Internal Trade (DPIIT) certification.',
        processingDays: '3–5 Working Days',
        whatsIncluded: ['DPIIT Recognition Certificate', 'Income Tax Exemption Guidance (80-IAC)', 'Fast-Track Patent / TM Subsidy Access'],
      },
    ],
  },
  {
    id: 'iso',
    title: 'ISO Registration',
    icon: '🏅',
    badge: '4 plans',
    subtitle: 'International Standards Certification (ISO 9001, 45001) for Global Credibility',
    targetForm: 'OtherSelectService',
    plans: [
      {
        id: 'iso-9001-iaf',
        name: 'ISO 9001:2015 (with IAF)',
        price: 6500,
        description: 'Globally recognized Quality Management System (QMS) with International Accreditation Forum (IAF) stamp.',
        processingDays: '3–5 Working Days',
        whatsIncluded: ['IAF Accredited Certificate', 'Global Tender Eligibility', '3-Year Surveillance Support', 'Soft & Hard Copy'],
      },
      {
        id: 'iso-9001-non-iaf',
        name: 'ISO 9001:2015 (without IAF)',
        price: 4500,
        description: 'Fast-track Quality Management System certificate for internal standardisation and domestic business.',
        processingDays: '2–3 Working Days',
        whatsIncluded: ['Non-IAF ISO Certificate', 'Quality Manual Guidelines', 'Instant Verifiable QR Code'],
      },
      {
        id: 'iso-45001-iaf',
        name: 'ISO 45001:2018 (with IAF)',
        price: 7500,
        description: 'Occupational Health & Safety Management System with international IAF accreditation.',
        processingDays: '4–6 Working Days',
        whatsIncluded: ['IAF Accredited Health & Safety Cert', 'Compliance Audit Checklist', 'International Tender Ready'],
      },
      {
        id: 'iso-45001-non-iaf',
        name: 'ISO 45001:2018 (without IAF)',
        price: 5500,
        description: 'Fast-track Occupational Health & Safety certificate for manufacturing & construction operations.',
        processingDays: '2–3 Working Days',
        whatsIncluded: ['ISO 45001 Certificate', 'Safety Documentation Kit', 'QR Code Verification'],
      },
    ],
  },
];

/**
 * Category 12: All Required Formats (Downloadable templates & legal formats)
 */
export const REQUIRED_FORMATS = [
  {
    id: 'format-noc',
    name: 'No Objection Certificate (NOC)',
    description: 'Standard Landlord / Owner NOC format for business address registration.',
    category: 'Property & Premises',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-noc-blood-rel',
    name: 'NOC for Blood Relative',
    description: 'NOC when premises is owned by Father, Mother, Spouse or Brother without rent.',
    category: 'Property & Premises',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-gst-auth-sig',
    name: 'GST Declaration for Authorised Signatory',
    description: 'Mandatory declaration format to appoint primary authorized signatory for GST.',
    category: 'GST Compliance',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-auth-letter',
    name: 'Authorisation Letter Format',
    description: 'General authority letter for regulatory departments, banks and tax authorities.',
    category: 'Corporate Legal',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-gst-board-res',
    name: 'GST Board Resolutions',
    description: 'Specimen board resolution for companies applying for GST registration.',
    category: 'GST Compliance',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-partnership-deed',
    name: 'Partnership Deed Format',
    description: 'Comprehensive legal draft covering profit-sharing, capital and dissolution clauses.',
    category: 'Partnership & LLP',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-rent-agreement-gst',
    name: 'Rent Agreement Format for GST Registration',
    description: 'Customized commercial lease agreement format fulfilling GST dept criteria.',
    category: 'Property & Premises',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-rent-free-noc',
    name: 'Rent Agreement Free NOC',
    description: 'Consent letter for operating trade without commercial rent agreement.',
    category: 'Property & Premises',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-fssai-decl',
    name: 'Declaration for Application Form for FSSAI Reg',
    description: 'Mandatory annexure declaration form required for FoSCoS food license issuance.',
    category: 'Food & FSSAI',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-dir-2',
    name: 'DIR-2 (Consent to Act as Director)',
    description: 'Form DIR-2 consent letter pursuant to Section 152(5) of Companies Act, 2013.',
    category: 'MCA & RoC',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-name-approval',
    name: 'Name Approval Format (RUN / SPICe+)',
    description: 'Format for main industrial objects and trademark no-objection for company name approval.',
    category: 'MCA & RoC',
    fileType: 'MCA / RoC',
  },
  {
    id: 'format-inc-9',
    name: 'INC-9 (Declaration by First Subscriber/Director)',
    description: 'Mandatory electronic INC-9 declaration format for new company incorporation.',
    category: 'MCA & RoC',
    fileType: 'PDF / DOC',
  },
  {
    id: 'format-dsc-board-res',
    name: 'Template-Board-Resolution for DSC',
    description: 'Board resolution format authorized by company to apply for Organization DSC.',
    category: 'Digital Signature',
    fileType: 'PDF / DOC',
  },
];
