'use client';

import React, { useState, useEffect } from 'react';
import StatusBadge from './StatusBadge';

export default function DocumentViewer({
  isOpen,
  onClose,
  document,
  onUpdateStatus,
}) {
  const [zoomLevel, setZoomLevel] = useState(1);
  const [currentStatus, setCurrentStatus] = useState('verified');
  const [remarks, setRemarks] = useState('');
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (document) {
      setCurrentStatus(document.status || 'verified');
      setRemarks(document.remarks || '');
      setZoomLevel(1);
    }
  }, [document]);

  if (!isOpen || !document) return null;

  const rawUrl = document.file_url || document.url || '';
  const isImage = rawUrl.match(/\.(jpeg|jpg|gif|png|webp)/i) ||
    rawUrl.includes('images.unsplash.com') ||
    document.type?.includes('image') ||
    document.mimeType?.includes('image') ||
    Boolean(document.name?.match(/\.(jpg|jpeg|png|webp|svg)/i));

  const isPdf = rawUrl.match(/\.pdf/i) ||
    document.type?.includes('pdf') ||
    document.mimeType?.includes('pdf') ||
    Boolean(document.name?.match(/\.pdf/i));

  const fileUrl = rawUrl || 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80';

  const handleSave = async () => {
    setSaving(true);
    try {
      if (onUpdateStatus) {
        await onUpdateStatus(document.id || document.key || document.name, currentStatus, remarks);
      }
    } finally {
      setSaving(false);
      onClose();
    }
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      window.print();
      return;
    }
    const docTitle = document.name || document.label || 'Document';
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${docTitle} — Vyapar Care</title>
          <style>
            body { margin: 0; padding: 24px; font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
            .header { display: flex; align-items: center; justify-content: space-between; border-bottom: 2px solid #1B2B5E; padding-bottom: 12px; margin-bottom: 20px; }
            .brand { font-size: 18px; font-weight: 800; color: #1B2B5E; letter-spacing: 0.5px; }
            .meta { font-size: 12px; color: #64748B; text-align: right; }
            .doc-container { text-align: center; margin-top: 20px; }
            img { max-width: 100%; max-height: 80vh; object-fit: contain; display: block; margin: 0 auto; border: 1px solid #E2E8F0; border-radius: 8px; }
            iframe { width: 100%; height: 85vh; border: 1px solid #E2E8F0; }
            .footer { margin-top: 24px; text-align: center; font-size: 11px; color: #94A3B8; border-top: 1px solid #E2E8F0; padding-top: 12px; }
            @media print {
              body { padding: 10mm; }
              @page { margin: 10mm; size: auto; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <div>
              <div class="brand">⚖️ VYAPAR CARE CONSULTANCY</div>
              <div style="font-size: 13px; font-weight: 600; color: #334155; margin-top: 2px;">Verification Attachment: ${docTitle}</div>
            </div>
            <div class="meta">
              <div>Printed On: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</div>
              <div>Status: ${document.status || 'Verified'}</div>
            </div>
          </div>
          <div class="doc-container">
            ${
              isImage
                ? `<img src="${fileUrl}" alt="${docTitle}" onload="setTimeout(function(){ window.print(); }, 400);" />`
                : `<iframe src="${fileUrl}"></iframe>`
            }
          </div>
          <div class="footer">
            Official Compliance & Verification Document — Generated by Vyapar Care Portal
          </div>
          <script>
            ${!isImage ? 'setTimeout(function(){ window.print(); }, 800);' : ''}
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-slate-950/80 backdrop-blur-md animate-fade-in no-print">
      <div
        className="relative w-full max-w-5xl bg-white rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[92vh] border border-slate-700/50"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Modal Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 bg-slate-900 text-white">
          <div className="flex items-center gap-3 min-w-0">
            <div className="w-10 h-10 rounded-xl bg-[#C5991A]/20 text-[#DFB53B] flex items-center justify-center text-xl shrink-0 font-bold">
              📄
            </div>
            <div className="min-w-0">
              <h3 className="text-base font-bold text-white truncate">
                {document.name || document.label || 'Document Preview'}
              </h3>
              <p className="text-xs text-slate-400 truncate">
                {document.fileName || document.file_name || (document.size ? `${document.size} • ` : '')}
                {document.uploaded_at ? `Uploaded ${new Date(document.uploaded_at).toLocaleDateString()}` : 'Uploaded Attachment'}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <StatusBadge status={document.status || 'uploaded'} className="bg-white/10 text-white border-white/20" />
            <button
              onClick={onClose}
              className="w-8 h-8 rounded-lg text-slate-400 hover:text-white hover:bg-white/10 flex items-center justify-center transition-colors font-bold text-lg"
              title="Close Preview"
            >
              ✕
            </button>
          </div>
        </div>

        {/* Modal Body: Preview Area */}
        <div className="flex-1 bg-slate-900 relative overflow-hidden flex items-center justify-center min-h-[380px] max-h-[58vh] p-4">
          {isImage ? (
            <div className="overflow-auto max-h-full max-w-full flex items-center justify-center p-2">
              <img
                src={fileUrl}
                alt={document.name || 'Document'}
                className="max-h-[50vh] max-w-full object-contain rounded-lg shadow-lg transition-transform duration-200 select-none"
                style={{ transform: `scale(${zoomLevel})` }}
              />
            </div>
          ) : isPdf && rawUrl.startsWith('http') ? (
            <iframe
              src={fileUrl}
              title={document.name || 'PDF Document'}
              className="w-full h-full min-h-[50vh] rounded-lg border-0 bg-white"
            />
          ) : (
            <div className="w-full h-full flex flex-col items-center justify-center p-8 text-center bg-slate-800/60 rounded-xl border border-slate-700 text-white">
              <div className="text-6xl mb-3">📑</div>
              <h4 className="font-bold text-white text-base mb-1">{document.name || 'Document Verification File'}</h4>
              <p className="text-xs text-slate-300 mb-5 max-w-md">
                Official regulatory document copy. Click below to open full size file or print directly.
              </p>
              <div className="flex items-center gap-3">
                <a
                  href={fileUrl}
                  target="_blank"
                  rel="noreferrer"
                  className="px-4 py-2 bg-[#C5991A] text-slate-950 rounded-lg text-xs font-bold hover:bg-[#DFB53B] transition-colors inline-flex items-center gap-1.5 shadow-md"
                >
                  Open in New Tab ↗
                </a>
                <button
                  onClick={handlePrint}
                  className="px-4 py-2 bg-white/10 hover:bg-white/20 text-white rounded-lg text-xs font-bold transition-colors inline-flex items-center gap-1.5 border border-white/20"
                >
                  🖨️ Print
                </button>
              </div>
            </div>
          )}

          {/* Zoom Controls for Images */}
          {isImage && (
            <div className="absolute bottom-4 right-4 flex items-center gap-1 bg-slate-950/80 backdrop-blur-md px-3 py-1.5 rounded-xl border border-slate-700 shadow-xl text-white">
              <button
                onClick={() => setZoomLevel((z) => Math.max(0.5, z - 0.25))}
                className="w-7 h-7 flex items-center justify-center rounded hover:bg-white/10 text-white font-bold text-sm"
                title="Zoom Out"
              >
                −
              </button>
              <span className="text-xs font-semibold px-2 text-slate-300 font-mono">
                {Math.round(zoomLevel * 100)}%
              </span>
              <button
                onClick={() => setZoomLevel((z) => Math.min(3, z + 0.25))}
                className="w-7 h-7 flex items-center justify-center rounded hover:bg-white/10 text-white font-bold text-sm"
                title="Zoom In"
              >
                +
              </button>
              <button
                onClick={() => setZoomLevel(1)}
                className="text-[11px] px-2 py-0.5 rounded text-slate-400 hover:text-white ml-1 border-l border-slate-700"
              >
                Reset
              </button>
            </div>
          )}
        </div>

        {/* Modal Footer: Status Update, Print & Download Actions */}
        <div className="p-4 sm:p-5 bg-white border-t border-slate-200 flex flex-col md:flex-row items-stretch md:items-center justify-between gap-4">
          <div className="flex-1 grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <label className="block text-[11px] font-bold uppercase tracking-wider text-slate-600 mb-1">
                Verification Status
              </label>
              <select
                value={currentStatus}
                onChange={(e) => setCurrentStatus(e.target.value)}
                className="admin-input text-xs py-2 bg-slate-50 font-semibold"
              >
                <option value="uploaded">Uploaded / Pending Verification</option>
                <option value="verified">Verified & Approved ✅</option>
                <option value="rejected">Rejected (Needs Re-upload) ❌</option>
                <option value="under_review">Under Scrutiny 🔍</option>
              </select>
            </div>

            <div>
              <label className="block text-[11px] font-bold uppercase tracking-wider text-slate-600 mb-1">
                Remarks / Scrutiny Note
              </label>
              <input
                type="text"
                value={remarks}
                onChange={(e) => setRemarks(e.target.value)}
                placeholder="e.g. Verified with portal records"
                className="admin-input text-xs py-2"
              />
            </div>
          </div>

          <div className="flex items-center justify-end gap-2 pt-2 md:pt-0 shrink-0">
            <button
              onClick={handlePrint}
              type="button"
              className="px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-800 text-xs font-bold rounded-lg transition-colors inline-flex items-center gap-1.5 border border-slate-300 shadow-sm"
              title="Print Document"
            >
              🖨️ Print
            </button>

            <a
              href={fileUrl}
              download={document.fileName || document.name || 'document'}
              target="_blank"
              rel="noreferrer"
              className="px-4 py-2 border border-slate-300 rounded-lg text-slate-800 text-xs font-bold hover:bg-slate-50 transition-colors inline-flex items-center gap-1.5 shadow-sm"
            >
              📥 Download
            </a>

            <button
              onClick={handleSave}
              disabled={saving}
              className="px-5 py-2 bg-[#1B2B5E] hover:bg-[#283E80] text-white text-xs font-bold rounded-lg transition-all shadow-sm disabled:opacity-50"
            >
              {saving ? 'Saving...' : 'Save & Close'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
